apiVersion: v1
kind: Service
metadata:
  name: fettle-angular
spec:
  type: NodePort
  selector:
    app: fettle-angular
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fettle-angular
  labels:
    app: fettle-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fettle-angular
  template:
    metadata:
      labels:
        app: fettle-angular
    spec:
      containers:
        - name: fettle-angular
          image: khalil15832/fettle-angular:latest
          ports:
            - containerPort: 4200
